version: '2'
services:
  ODS-Rest-Api:
    image: ${ods_docker_registry}/ods-rest-api:${ods_docker_tag}
    environment:
      DATABASE_URL: postgresql://${ods_database_user}:@${ods_database_host}:${ods_database_port}/${ods_database}
      APP_HOSTNAME: http://${ods_service_host}:${ods_service_port}/api
    ports:
    - ${ods_service_host}:5000/tcp
    labels:
      io.rancher.container.pull_image: always
    volumes:
    - ${ods_splunk_rancher_host_sharedvolume_path}:${ods_log_folder}
    tty: true
    stdin_open: true

  splunkuniversalforwarder:
    hostname: splunkuniversalforwarder-${ods_splunk_datasource_label}
    image: splunk/universalforwarder:7.0.0
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_FORWARD_SERVER: ${ods_splunk_indexer_host}:${ods_splunk_indexer_data_port}
      SPLUNK_ADD: "monitor ${ods_splunk_forwarder_logs_mount_path}/${ods_log_filename}"
    volumes:
    - ${ods_splunk_rancher_host_sharedvolume_path}:${ods_splunk_forwarder_logs_mount_path}


