version: '2'
services:
  ODS-Rest-Api:
    image: ${ODS_DOCKER_REGISTRY}/ods-rest-api:${ODS_DOCKER_TAG}
    environment:
      DATABASE_URL: postgresql://${ODS_DATABASE_USER}:@${ODS_DATABASE_HOST}:${ODS_DATABASE_PORT}/${ODS_DATABASE}
      APP_HOSTNAME: http://${ODS_SERVICE_HOST}:${ODS_SERVICE_PORT}/api
    ports:
    - ${ODS_SERVICE_PORT}:5000/tcp
    labels:
      io.rancher.container.pull_image: always
    volumes:
    - ${ODS_SPLUNK_RANCHER_HOST_SHAREDVOLUME_PATH}:${ODS_LOG_FOLDER}
    tty: true
    stdin_open: true

  splunkuniversalforwarder:
    hostname: splunkuniversalforwarder-${ODS_SPLUNK_DATASOURCE_LABEL}
    image: splunk/universalforwarder:7.0.0
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_FORWARD_SERVER: ${ODS_SPLUNK_INDEXER_HOST}:${ODS_SPLUNK_INDEXER_DATA_PORT}
      SPLUNK_ADD: "monitor ${ODS_SPLUNK_FORWARDER_LOGS_MOUNT_PATH}/${ODS_LOG_FILENAME}"
    volumes:
    - ${ODS_SPLUNK_RANCHER_HOST_SHAREDVOLUME_PATH}:${ODS_SPLUNK_FORWARDER_LOGS_MOUNT_PATH}
