.catalog:
  name: "NHS Digital - ODS App"
  version: "0.1"
  description: "NHS Digital - ODS App"
  minimum_rancher_version: "v1.1.4"
  questions:
    - variable: "ODS_DOCKER_REGISTRY"
      description: "The address of ODS Docker registry"
      label: "Docker Registry"
      required: true
      default: markharrison17
      type: "string"
    - variable: "ODS_DOCKER_TAG"
      description: "Docker Tag"
      label: "For example latest"
      required: true
      default: ptl
      type: "string"
    - variable: "ODS_DATABASE_USER"
      description: "Databse User"
      label: "The database username"
      required: true
      default: postgre
      type: "string"
    - variable: "ODS_DATABASE_HOST"
      description: "IP of the Database host"
      label: "The IP address of the database host"
      required: true
      default: 52.215.50.215
      type: "string"
    - variable: "ODS_DATABASE_PORT"
      description: "Databse Port"
      label: "The default database port"
      required: true
      default: 5432
      type: "string"
    - variable: "ODS_DATABASE"
      description: "Database name"
      label: "The database name"
      required: true
      default: openods
      type: "string"
    - variable: "ODS_SERVICE_HOST"
      description: "IP address of ODS API"
      label: "ODS API address"
      required: true
      default: "https://ods-tf.ods-tf.cis.spine2.ncrs.nhs.uk"
      type: "string"
    - variable: "ODS_SERVICE_PORT"
      description: "Port of ODS API"
      label: "ODS Service port"
      required: true
      default: "8080"
      type: "string"
    - variable: "ODS_SPLUNK_RANCHER_HOST_SHAREDVOLUME_PATH"
      description: "Location for splunk shared volume"
      label: "Splunk shared volume path"
      required: true
      default: portable
      type: "string"
    - variable: "ODS_SPLUNK_DATASOURCE_LABEL"
      description: "Label for splunk datasource"
      label: "Splunk datasource label"
      required: true
      default: "dev"
      type: "string"
    - variable: "ODS_SPLUNK_INDEXER_HOST"
      description: "Splunk indexer host location"
      label: "Splunk indexer IP address"
      required: true
      default: "1.2.3.4"
      type: "string"
    - variable: "ODS_SPLUNK_INDEXER_DATA_PORT"
      description: "Splunk forwarder data port"
      label: "Splunk indexer data port"
      required: true
      default: "9997"
      type: "string"
    - variable: "ODS_SPLUNK_FORWARDER_LOGS_MOUNT_PATH"
      description: "Splunk forwarder logs mount path"
      label: "Splunk forwarder mount path"
      required: true
      default: "/var/log/ods"
      type: "string"
    - variable: "ODS_LOG_FILENAME"
      description: "ODS log filename"
      label: "Log filename"
      required: true
      default: "ods.log"
      type: "string"

ODS-Rest-Api:
  scale: 1
  health_check:
    port: 5000
    interval: 2000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 1000
    request_line: GET / HTTP/1.0
    healthy_threshold: 2
    initializing_timeout: 15000
    reinitializing_timeout: 15000

splunkuniversalforwarder:
  scale: 1