.catalog:
  name: "NHS Digital - ODS App"
  version: "0.1"
  description: "NHS Digital - ODS App"
  minimum_rancher_version: "v1.1.4"

ODS-Rest-Api:
  scale: 1
  health_check:
    port: 5000
    interval: 2000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 1000
    request_line: GET / HTTP/1.0
    healthy_threshold: 2
    initializing_timeout: 15000
    reinitializing_timeout: 15000

splunkuniversalforwarder:
  scale: 1